spring:
  # test h2 db
  datasource:
    platform: h2
    url: jdbc:h2:~/test
    username: root
    password: root
    driver-class-name: org.h2.Driver
    # 每次启动程序,都会执行该SQL脚本
    schema: classpath:db/schema.sql
    # 每次启动程序,都会执行该SQL脚本
    data: classpath:db/data.sql
    sql-script-encoding: utf-8
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
logging:
  path: /var/log/spring-boot-assembly
  file: /var/log/spring-boot-assembly/dev.log
  level:
    org.hibernate: INFO