spring:
  datasource:
    driverclassname: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate.ddl-auto: none
logging:
  path: /var/log/spring-boot-assembly
  file: /var/log/spring-boot-assembly/prod.log
  level:
    org.hibernate: INFO
